Adding lib unit tests
scambier/obsidian-text-extractor pull request #61
Opened 2024-07-11 21:30 UTC by WhatIsHeDoing

I love this plugin, and noticed PRs were welcome, so thought I'd start learning the codebase by adding unit tests. Hope this actually helps!

Started with lib utils and believe the tests identify and fix some small edge cases. Happy to expand the coverage if this is the right direction.

2024-07-14 07:03 UTC, scambier requested changes
Thanks for your PR 👍

Could you just re-add the `$` in front of the command lines? Thank you.

2024-07-14 07:03 UTC, scambier commented on lib/README.md
> +pnpm i
The `$` is a convention to indicate the command is meant to be run as a normal user (as opposed to `#` for a root user). It's also a useful visual indicator when long lines wrap around, though it's not the case here :)

2024-07-14 07:03 UTC, scambier commented on lib/README.md
> +pnpm test
$ here too

2024-07-14 07:03 UTC, scambier commented on lib/README.md
> +pnpm coverage
$ here too

2024-07-15 16:42 UTC, WhatIsHeDoing commented
Ah no problem, I removed them as they were highlighted by the markdownlint [MD014](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md014.md) warning.

2024-07-15 16:50 UTC, merged

2024-07-15 16:51 UTC, scambier commented
Thanks 👍
That's quite an opinionated linter 😅